hackernews/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required as auth
from django.contrib import admin
admin.autodiscover()

from hacker.views import List_View
from hacker.views import Detail_View
from hacker.views import UserDetailView
from hacker.views import UserEditView
from hacker.views import Create_View
from hacker.views import Update_View
from hacker.views import Delete_View
from hacker.views import VoteFormView
urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include("django.contrib.comments.urls")),
    url(r'^$', List_View.as_view(), name='home'),

    url(r"^login/$", "django.contrib.auth.views.login",
        {"template_name": "login.html"}, name="login"),
    url(r"^logout/$", "django.contrib.auth.views.logout_then_login",
        name="logout"),

   
    url(r"^users/(?P<slug>\w+)/$", UserDetailView.as_view(),
        name="profile"),
    url(r"edit_profile/$", auth(UserEditView.as_view()),
        name="edit_profile"),

    url(r"^link/create/$", auth(Create_View.as_view()),
        name="link_create"),
    url(r"^link/(?P<pk>\d+)$", Detail_View.as_view(),
        name="link_detail"),
    url(r"^link/update/(?P<pk>\d+)/$", auth(Update_View.as_view()),
        name="link_update"),
    url(r"^link/delete/(?P<pk>\d+)/$", auth(Delete_View.as_view()),
        name="link_delete"),

    url(r'^vote/$', auth(VoteFormView.as_view()), name="vote"),
    )

hacker/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Count
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.utils import timezone

class LikeCounter(models.Manager):
    def get_query(self):
        return super(LikeCounter, self).get_query().annotate(
            votes=Count('vote')).order_by('-ranking', '-votes')


class Link(models.Model):
    title = models.CharField("Headline", max_length=100)
    submit_by = models.ForeignKey(User)
    submit_on = models.DateTimeField(default=timezone.now())
    ranking = models.FloatField(default=0.0)
    url = models.URLField("URL", max_length=100, blank=True)
    description = models.TextField(blank=True)

    likes =  LikeCounter()
    objects = models.Manager()            # default manager

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("link_detail", kwargs={"pk": str(self.id)})

    def ranker(self):

        HOUR = float(60*60)
        Weight = 1.2

        tec = timezone.now() - self.submit_on
        item_time = tec.total_seconds() // HOUR
        votes = self.votes - 1
        self.ranking = votes / pow((item_time+2), Weight)
        self.save()

class Like(models.Model):
    liker = models.ForeignKey(User)
    link = models.ForeignKey(Link)

    def __unicode__(self):
        return "%s voted %s" % (self.liker.username, self.link.title)

class User(models.Model):
    user = models.OneToOneField(User, unique=True)
    # Extra attributes
    details = models.TextField(null=True)

    def __unicode__(self):
        return "%s's profile" % self.user

def profile_creator(sender, instance, created, **kwargs):
    if created:
        profile, created = User.objects.get_or_create(user=instance)


post_save.connect(profile_creator, sender=User)

hacker/forms.py
from django import forms
from .models import User
from .models import Link
from .models import  Like

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        exclude = ("user",)

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        exclude = ("submit_by", "ranker")

class LikeForm(forms.ModelForm):
    class Meta:
        model = Like

hacker/views.py
import json
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from django.views.generic import DetailView
from .models import Link
from .models import User
from .models import  Like
from .forms import UserProfileForm
from .forms import LinkForm
from .forms import LikeForm

from django.contrib.auth import get_user_model
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import FormView
from django.core.urlresolvers import reverse, reverse_lazy

from django.contrib.comments.models import Comment



    
class Detail_View(DetailView):
    model = Link

class Create_View(CreateView):
    model = Link
    form_class = LinkForm

    def form_valid(self, form):
        f1 = form.save(commit=False)
        f1.ranker = 0.0
        f1.submit_by = self.request.user
        f1.save()
        return super(Create_View, self).form_valid(form)

class Update_View(UpdateView):
    model = Link
    form_class = LinkForm

class Delete_View(DeleteView):
    model = Link
    success_url = reverse_lazy("home")

class UserDetailView(DetailView):
    model = get_user_model()
    slug_field = "username"
    template_name = "user_detail.html"

    def get_object(self, queryset=None):
        user = super(UserDetailView, self).get_object(queryset)
        User.objects.get_or_create(user=user)
        return user

class UserEditView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = "edit_profile.html"

    def get_object(self, queryset=None):
        return User.objects.get_or_create(user=self.request.user)[0]

    def get_success_url(self):
        return reverse("profile", kwargs={"slug": self.request.user})


class JSON_in(object):
    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict), content_type='application/json')
        response.status = 200 if valid_form else 500
        return response

class Like_form_View(FormView):
    form_class = LikeForm

    def create_response(self, vdict=dict(), valid_form=True):
        response = HttpResponse(json.dumps(vdict))
        response.status = 200 if valid_form else 500
        return response

    def form_valid(self, form):
        link = get_object_or_404(Link, pk=form.data["link"])
        user = self.request.user
        p_likes =  Like.objects.filter(voter=user, link=link)
        h_liked = (len(p_likes) > 0)

        ret = {"success": 1}
        if not h_liked:
            # add vote
            v =  Like.objects.create(liker=user, link=link)
            ret["likeobj"] = v.id
        else:
            # delete vote
            p_likes[0].delete()
            ret["unliked"] = 1
        return self.create_response(ret, True)


    def form_invalid(self, form):
        ret = {"success": 0, "form_errors": form.errors }
        return self.create_response(ret, False)

class Random(object):
    def get_context_data(self, **kwargs):
        context = super(Random, self).get_context_data(**kwargs)
        context[u"randomquip"] = Comment.objects.order_by('?')[0]
        return context

class List_View(Random, ListView):
    model = Link
    queryset = Link.likes.all()
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(List_View, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            liked =  Like.objects.filter(liker=self.request.user)
            links_in_page = [link.id for link in context["object_list"]]
            liked = liked.filter(link_id__in=links_in_page)
            liked = liked.values_list('link_id', flat=True)
            context["voted"] = liked
        return context

class VoteFormView(JSON_in,  Like_form_View):
    pass

hackernews/templates/base.html
<html>
<head>
  <title>Hacker News</title>
  <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css" />
  <script src="{{ STATIC_URL }}js/jquery.min.js"></script>
  <script src="{{ STATIC_URL }}js/vote.js"></script>
</head>
<body>
<h1>Hacker News</h1>

{% block content %}
{% endblock %}

<footer>
  <p>
    <a href="{% url 'home' %}">Home</a> |
{% if user.is_authenticated %}
    <a href="{% url 'link_create' %}">Submit Link</a> |
    <a href="{% url 'logout' %}">Logout</a> |
    <a href="{% url 'profile' slug=user.username %}"><b>{{ user.username }}</b></a>
{% else %}
    <a href="{% url 'registration_register' %}">Register</a> |
    <a href="{% url 'login' %}">Login</a> 
{% endif %}
  </p>
</footer>
</body>
</html>

hackernews/templates/edit_profile.html
{% extends "base.html" %}

{% block content %}
<h2>{{ user.username }}'s Profile</h2>
<div class="container">
		<br />
		<div class="panel panel-primary">
        <div class="panel-heading">

        </div>
        <div class="panel-body">
        <div class="table-responsive">

            <form method="post" action="">
              {% csrf_token %}
              {{ form.as_p }}
              <input type="submit" value="Edit">
            </form>

 </div>
    </div>
    </div>
    </div>

{% endblock %}

hackernews/templates/hacker/link_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<p>Are you sure you want to delete "{{ object.title }}"?</p>

<form method="post" action="{% url 'link_delete' pk=object.pk %}">
  {% csrf_token %}
  <a href="{% url 'link_detail' pk=object.pk %}">Go back</a> 
  <p><input type="submit" value="Confirm deletion" /></p>
</form> 

{% endblock %}

hackernews/templates/hacker/link_detail.html
{% extends "base.html" %}
{% load comments %}


<a href="{% url 'link_detail' pk=link.pk %}">
<b>{{ link.title }}</b>
 {% get_comment_count for link as comment_count %}
 {{ comment_count }} comment{{ comment_count|pluralize }}
</a>



{% block content %}
<style>
  #id_honeypot {
    display: none;
  }
</style>

<h2><a href="{{ object.link }}">{{ object.title }}</a></h2>
{% if object.submitter == user %}
  <a href="{% url 'link_update' pk=object.pk %}">Edit</a> | 
  <a href="{% url 'link_delete' pk=object.pk %}">Delete</a>
{% endif %}

<div class="desc">
  {{ object.description }}
</div>

<div class="comments">
  <h3>Comments</h3>

  <div class="comment_form">
{% if user.is_authenticated %}
  {% get_comment_form for object as form %}
  <form action="{% comment_form_target %}" method="POST">
    {% csrf_token %}
    {{ form.comment }}
    {{ form.honeypot }}
    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}
    <input type="hidden" name="name" value="{{ user }}" />
    <input type="hidden" name="email" value="{{ user.email|default:'d@ummy.com' }}" />
    <input type="hidden" name="url" value="" />
    <input type="hidden" name="next" 
	   value="{% url 'link_detail' pk=object.id %}" />
    <input type="submit" value="Add comment" id="id_submit" />
  </form>
{% else %}
  <p>Please <a href="{% url 'login' %}">log in
  </a> to leave a comment.</p>
{% endif %}
  </div>


  {% render_comment_list for object %}
</div>


{% endblock %}

hackernews/templates/hacker/link_form.html
{% extends "base.html" %}

{% block content %}
<div class="container">
		<br />
		<div class="panel panel-primary">
        <div class="panel-heading">

        </div>
        <div class="panel-body">
        <div class="table-responsive">

		<table class="table">
        <form method="post" action="">
         {% csrf_token %}
         {{ form.as_p }}

  <input type="submit" class="btn btn-default" data-dismiss="modal" value="Add">
</form>

    </table>
    </div>
    </div>
    </div>
    </div>

{% endblock %}

hackernews/templates/hacker/link_list.html
{% extends "base.html" %}
{% load comments %}

{% block content %}
{% if is_paginated %}
<ol start="{{ page_obj.start_index }}">
{% else %}
<ol>
{% endif %}
{% for link in object_list %}
<form method="post" action="{% url 'vote' %}" class="vote_form">
  <li> [{{ link.votes }}]
    {% csrf_token %}
    <input type="hidden" id="id_link" name="link" class="hidden_id" value="{{ link.pk }}" />
    <input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
    {% if not user.is_authenticated %}
    <button disabled title="Please login to like">+</button>
    {% elif link.pk not in voted %}
    <button>+</button>
    {% else %}
    <button>-</button>
    {% endif %}
    <a href="{% url 'link_detail' pk=link.pk %}">
      <b>{{ link.title }}</b>
      {% get_comment_count for link as comment_count %}
      {{ comment_count }} comment{{ comment_count|pluralize }}
    </a>
  </li>
</form>
{% endfor %}
</ol>
{% if is_paginated %}
<div class="pagination">
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">More &raquo;</a>
    {% endif %}
</div>
{% endif %}
<blockquote style="background-color: #ddd; padding: 4px; border-radius: 10px; margin: 10px 0; color: #666; font-size: smaller; text-shadow: rgba(255,255,255,0.8) 1px 1px 0;">
{{ randomquip.comment|truncatechars:140 }}
</blockquote>
{% endblock %}

hackernews/templates/list.html
{% extends "base.html" %}
{% load comments %}

{% block content %}
{% if is_paginated %}
<ol start="{{ page_obj.start_index }}">
{% else %}
<ol>
{% endif %}
{% for link in object_list %}
<form method="post" action="{% url 'vote' %}" class="vote_form">
  <li> [{{ link.votes }}]
    {% csrf_token %}
    <input type="hidden" id="id_link" name="link" class="hidden_id" value="{{ link.pk }}" />
    <input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}" />
    {% if not user.is_authenticated %}
    <button disabled title="Please login to like">+</button>
    {% elif link.pk not in voted %}
    <button>+</button>
    {% else %}
    <button>-</button>
    {% endif %}
    <a href="{% url 'link_detail' pk=link.pk %}">
      <b>{{ link.title }}</b>
      {% get_comment_count for link as comment_count %}
      {{ comment_count }} comment{{ comment_count|pluralize }}
    </a>
  </li>
</form>
{% endfor %}
</ol>
{% if is_paginated %}
<div class="pagination">
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">More &raquo;</a>
    {% endif %}
</div>
{% endif %}
<blockquote style="background-color: #ddd; padding: 4px; border-radius: 10px; margin: 10px 0; color: #666; font-size: smaller; text-shadow: rgba(255,255,255,0.8) 1px 1px 0;">
{{ randomquip.comment|truncatechars:140 }}
</blockquote>
{% endblock %}

hackernews/templates/login.html
{% extends "base.html" %}

{% block content %}
<h2>Login</h2>

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}
<div class="container">
		<br />
		<div class="panel panel-primary">
        <div class="panel-heading">

        </div>
        <div class="panel-body">
        <div class="table-responsive">

            <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
              {% csrf_token %}
              <table>
                <tr>
                    <div id="form">
                        <div class="form-group">
                           <td>{{ form.username.label_tag }}</td>
                            </div>
                        <div class="form-group">
                            <td>{{ form.username }}</td>
                            </div>
                    </div>
                </tr>
                <tr>
                  <td>{{ form.password.label_tag }}</td>
                  <td>{{ form.password }}</td>
                </tr>
              </table>
  
  <input type="submit" value="login" />
  <input type="hidden" name="next" value="{{ next }}" />
</form>
    </div>
    </div>
    </div>
    </div>


{% endblock %}

hackernews/templates/user_detail.html
{% extends "base.html" %}

{% block content %}

<h2>{{ object.username }}'s Profile</h2>
    <div class="container">
		<br />
		<div class="panel panel-primary">
        <div class="panel-heading">

        </div>
        <div class="panel-body">
        <div class="table-responsive">

                    {% if object.userprofile.bio %}
                    <div>
                <b>Bio:</b>
                {{ object.userprofile.bio }}
                    </div>
                    {% endif %}
                {% if object.username == user.username %}
                <p><a href='{% url "edit_profile" %}'>Edit my profile</a></p>
                {% endif %}
     </div>
    </div>
    </div>
    </div>


{% endblock %}